# Generated by Django 4.2.7 on 2023-12-01 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.AutoField(primary_key=True, serialize=False)),
                ('room_count', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('has_tv', models.BooleanField()),
                ('has_fridge', models.BooleanField()),
                ('capacity', models.IntegerField()),
                ('category', models.CharField(choices=[('standard', 'Звичайний'), ('semi_luxury', 'Полу Люкс'), ('luxury', 'Люкс')], max_length=50)),
                ('cost_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_code', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('stay_duration', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room')),
            ],
        ),
    ]
